blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://github.com/katiem0/gh-bbc-exporter/discussions
    about: Please ask and answer questions here.
  - name: GitHub Documentation
    url: https://github.com/katiem0/gh-bbc-exporter/tree/main/docs
    about: Check out the documentation for help.