name: Security Checks

permissions:
  contents: read
  security-events: write

on:
  push:
    branches: [main]
  pull_request:

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v0.32.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          
      - name: Run gosec Security Scanner
        uses: securego/gosec@v2.22.7
        with:
          args: '-fmt sarif -out gosec-results.sarif ./...'
          
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gosec-results.sarif
          
      - name: Check for hardcoded secrets
        uses: trufflesecurity/trufflehog@v3.90.3
        with:
          path: ./
          
      - name: Test environment variable support
        run: |
          # Ensure environment variables work correctly
          export BITBUCKET_TOKEN="test-token"
          go test ./cmd -run TestEnvironment -v